export enum Operation {
  ACCESS_BACK_OFFICE = 'OP_ACCESS_BACK_OFFICE',
  INSERT_DOCUMENT_TO_MY_PERSONAL_SPACE = 'OP_INSERT_DOCUMENT_TO_MY_PERSONAL_SPACE',
  INSERT_DOCUMENT_TO_ALL_USERS = 'OP_INSERT_DOCUMENT_TO_ALL_USERS',
  LIST_MY_DOCUMENTS = 'OP_LIST_MY_DOCUMENTS',
  DOWNLOAD_MY_DOCUMENT = 'OP_DOWNLOAD_MY_DOCUMENT',
}
